[env]
TARGET="riscv64gc-unknown-none-elf"
OUTDIR = "target/${TARGET}/debug"
RV6_LIB = "${OUTDIR}/librv6.a"
RV6_ELF = "${OUTDIR}/rv6"
RV6_BIN = "${OUTDIR}/rv6.bin"

[tasks.build]
command = "cargo"
args = ["build", "--target", "${TARGET}"]

[tasks.link]
command = "riscv64-unknown-elf-ld"
args = ["--gc-sections", "-T", "linkers/riscv.ld", "-o", "${RV6_ELF}", "${RV6_LIB}" ]
dependencies = ["build"]

[tasks.objcopy]
command = "riscv64-unknown-elf-objcopy"
args = ["-O", "binary", "${RV6_ELF}", "${RV6_BIN}"]
dependencies = ["link"]

[tasks.run]
command = "qemu-system-riscv64"
args = [
    "-M", "virt",
    "-m", "256M",
    "-nographic",
    "-serial", "mon:stdio",
    "-bios", "../opensbi/build/platform/generic/firmware/fw_jump.bin",
    "-kernel", "${RV6_BIN}"
]
dependencies = ["objcopy"]