[env]
RV6_BIN = "target/riscv64gc-unknown-none-elf/debug/rv6.bin"

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.objcopy]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "${RV6_BIN}"]
dependencies = ["build"]

[tasks.run]
command = "qemu-system-riscv64"
args = [
    "-M", "virt",
    "-m", "256M",
    "-nographic",
    "-serial", "mon:stdio",
    "-bios", "../opensbi/build/platform/generic/firmware/fw_jump.bin",
    "-kernel", "${RV6_BIN}"
]
dependencies = ["objcopy"]