[build]
rustflags = ['-Clink-arg=-Tsrc/lds/qemu.ld']
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = "qemu-system-riscv32 -machine virt -cpu rv32 -smp 1 -m 128M -nographic -serial mon:stdio -bios none -s -kernel"
