[build]
rustflags = ['-Clink-arg=-Tsrc/cpu/qemu/qemu-virt.ld']
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -cpu rv64 -smp 1 -m 128M -nographic -serial mon:stdio -bios none -s -kernel"
