[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
name = "kmm"
version = "0.1.0"

[dependencies]
bitflags = "1.2.1"
spin = "0.7.1"

[dev-dependencies]
lazy_static = "1.4.0"
