[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
name = "riscv"
version = "0.1.0"

[dependencies]
bitflags = "1.2.1"
kmm = {path = "../kmm"}

[features]
default = ["sv48"]
sv39 = []
sv48 = []
